# Generated by Django 4.2 on 2023-04-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='foundation',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
